INSERT INTO jobs (company, location, title, description, company_link, posting_link, primary_contact_name, primary_contact_position, primary_contact_email, primary_contact_phone, salary, notes, stage)
VALUES ('Nitor Infotech Inc', 'Chicago, IL', 'Web Developer - Intern', 'internship', 'https://www.nitorinfotech.com/', 'https://www.indeed.com/cmp/Nitor-Infotech/jobs/Web-Developer-f97166ba82bdaea3?q=Web+Developer&vjs=3', 'Bob Smith', 'Hiring Manager', 'bob.smith@notor.net', '666-666-6666', '60000', 'misc. notes', 'applied');

INSERT INTO jobs (company, location, title, description, company_link, posting_link, primary_contact_name, primary_contact_position, primary_contact_email, primary_contact_phone, salary, notes, stage)
VALUES ('The University of Chicago', 'Chicago, IL', 'Front-End Web Developer', 'research computing center', 'https://rcc.uchicago.edu/', 'https://www.indeed.com/viewjob?jk=186e482104575417&tk=1ci2ad230a3tmbje&from=serp&vjs=3', 'Jane Smith', 'Hiring Manager', 'jane.smith@uchicago.net', '777-777-7777', '40000', 'misc. notes', 'phone interviewed');

INSERT INTO jobs (company, location, title, description, company_link, posting_link, primary_contact_name, primary_contact_position, primary_contact_email, primary_contact_phone, salary, notes, stage)
VALUES ('Google', 'Sunnyvale, CA', 'Software Engineer', 'Google software engineer', 'https://www.google.com/', 'https://careers.google.com/jobs#!t=jo&jid=/google/software-engineer-1160-n-mathilda-ave-sunnyvale-ca-94089-3712430923&f=true&', 'Chris Adams', 'Engineering Manager', 'chris.adams@gmail.com', '888-888-8888', '80000', 'misc. notes', 'in person interviewed');

INSERT INTO jobs (company, location, title, description, company_link, posting_link, primary_contact_name, primary_contact_position, primary_contact_email, primary_contact_phone, salary, notes, stage)
VALUES ('New York Film Academy', 'New York, NY', 'Jr. Front End Programmer', 'web developer', 'https://www.nyfa.edu/', 'https://www.indeed.com/viewjob?jk=1932dc82882c2117&tk=1ci2flsnha3tmb44&from=serp&vjs=3', 'Mary Smith', 'Hiring Manager', 'mary.smith@nyfa.com', '555-555-5555', '65000', 'misc. notes', 'archived');

INSERT INTO jobs (company, location, title, description, company_link, posting_link, primary_contact_name, primary_contact_position, primary_contact_email, primary_contact_phone, salary, notes, stage)
VALUES ('Wicket Labs', 'Seattle, WA', 'Web UI/UX Developer', 'We are seeking a developer with an eye for design to help our product. The ideal candidate has strong skills in front-end technology and a track record of building great user experiences.', 'https://www.wicketlabs.com/', 'https://www.indeed.com/viewjob?jk=7375155af1570cc5&q=Web+Developer&l=Seattle%2C+WA&tk=1ci2gli61a3tmbpl&from=web&vjs=3', 'John Rob', 'Architect', 'john.rob@wicketlabs.com', '444-444-4444', '77000', 'misc. notes', 'offered');